inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 200

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/CollectionMethods:
  PreferredMethods:
    find: detect

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
