inherit_from: .rubocop_todo.yml

Lint/EndAlignment:
  AlignWith: variable

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignore

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals
