sudo: false

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - rbx

gemfile:
  - gemfiles/rails.3.2.gemfile
  - gemfiles/rails.4.0.gemfile
  - gemfiles/rails.4.1.gemfile
  - gemfiles/rails.4.2.gemfile

matrix:
  allow_failures:
    - rvm: rbx
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails.3.2.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails.3.2.gemfile
