sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - rbx

gemfile:
  - gemfiles/rails.3.2.gemfile
  - gemfiles/rails.4.0.gemfile
  - gemfiles/rails.4.1.gemfile
  - gemfiles/rails.4.2.gemfile

matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails.3.2.gemfile
