sudo: false

rvm:
  - 2.2.5
  - 2.3.1
  - rbx

gemfile:
  - gemfiles/rails.4.0.gemfile
  - gemfiles/rails.4.1.gemfile
  - gemfiles/rails.4.2.gemfile
  - gemfiles/rails.5.0.gemfile

matrix:
  allow_failures:
    - rvm: rbx

script:
  - bundle exec rspec
  - bundle exec rubocop
